SEARCH_QUERIES = {
    "1": 'os:"Windows XP"',
    "2": 'product:"MySQL"',
    "3": 'product:"Jenkins"',
    "4": 'title:"Webcam"',
    "5": 'product:"MongoDB"',
    "6": 'product:"Elasticsearch"',
    "7": 'title:"IP Camera"',
    "8": 'product:"Kibana"',
    "9": 'product:"Hadoop"',
    "10": 'title:"DVR Login"',
    "11": 'port:502 name:"Modbus"',
    "12": 'port:102 name:"Siemens S7"',
    "13": 'port:44818 name:"EtherNet/IP"',
    "14": 'port:47808 name:"BACnet"',
    "15": 'port:20000 name:"DNP3"',
    "16": 'product:"HP Printer"',
    "17": 'product:"vsftpd"',
    "18": 'port:23',
    "19": 'product:"Apache httpd"',
    "20": 'product:"Redis"',
    "21": 'product:"Oracle DB"',
    "22": 'http.title:"WordPress"',
    "23": 'http.title:"Joomla"',
    "24": 'http.title:"Drupal"',
    "25": 'http.title:"phpBB"',
    "26": 'http.title:"vBulletin"',
    "27": 'port:5900 product:VNC',
    "28": 'port:3389 product:Terminal Services',
    "29": 'product:"Siemens PLC"',
    "30": 'product:"D-Link Router"',
    "31": 'product:"MikroTik Router"',
    "32": 'product:"Netgear Router"',
    "33": 'product:"QNAP NAS"',
    "34": 'product:"VoIP Phone"',
    "35": 'ip:"SPECIFIC_IP"',  # Placeholder for specific IP search
    "36": 'port:2905 protocol:ss7'
}
